#!/bin/sh
exec 1<&-
exec 1<>"../user/wordlist.php"

echo "<?php"
echo "/**"
echo " * ***************************************************************"
echo " * wordlist.php - Autogenerated from words.txt"
echo " * ***************************************************************"
echo " */"
echo ""
echo "\$words = array("
for i in `cat words.txt`; do
    echo "                \"$i\","
done
echo "                \"\");"
echo "array_pop(\$words);"
